import getAllCookies from './modules/get_all_cookies.mjs';
import saveToFile from './modules/save_to_file.mjs';

// ---------------------------------------------------------------------------
// Configuration — must match the SageDLP cookie server defaults
// ---------------------------------------------------------------------------
const SAGEDLP_SERVER_URL = 'http://127.0.0.1:9876/api/cookies';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Serialize cookies to Netscape format text.
 */
const serializeNetscape = (cookies) => {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# http://curl.haxx.se/rfc/cookie_spec.html',
    '# This file was auto-generated by SageDLP',
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith('.')
      ? cookie.domain
      : '.' + cookie.domain;
    const includeSub = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.session
      ? '0'
      : String(Math.floor(cookie.expirationDate || 0));
    const name = cookie.name || '';
    const value = cookie.value || '';

    lines.push(
      [domain, includeSub, path, secure, expiry, name, value].join('\t'),
    );
  }

  return lines.join('\n') + '\n';
};

/**
 * Post cookie data to the local SageDLP server silently.
 * Failures are logged to console only — never show a user-facing error.
 */
const postCookiesToServer = async (urlString) => {
  if (!urlString) return;
  try {
    const url = new URL(urlString);
    const cookies = await getAllCookies({
      url: url.href,
      partitionKey: { topLevelSite: url.origin },
    });
    if (!cookies.length) return;

    const cookiesText = serializeNetscape(cookies);

    await fetch(SAGEDLP_SERVER_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        cookies: cookiesText,
        url: url.href,
        source: 'extension',
      }),
    });
  } catch (_err) {
    // Silently ignore — server may not be running
  }
};

// ---------------------------------------------------------------------------
// Badge counter (original functionality preserved)
// ---------------------------------------------------------------------------

const updateBadgeCounter = async () => {
  const [tab] = await chrome.tabs.query({
    active: true,
    currentWindow: true,
  });
  if (!tab) {
    return;
  }
  const { id: tabId, url: urlString } = tab;
  if (!urlString) {
    chrome.action.setBadgeText({ tabId, text: '' });
    return;
  }
  const url = new URL(urlString);
  const cookies = await getAllCookies({
    url: url.href,
    partitionKey: { topLevelSite: url.origin },
  });
  const text = cookies.length.toFixed();
  chrome.action.setBadgeText({ tabId, text });

  // --- AUTO-POST cookies to SageDLP server whenever the badge updates ---
  postCookiesToServer(urlString);
};

chrome.cookies.onChanged.addListener(updateBadgeCounter);
chrome.tabs.onUpdated.addListener(updateBadgeCounter);
chrome.tabs.onActivated.addListener(updateBadgeCounter);
chrome.windows.onFocusChanged.addListener(updateBadgeCounter);

// ---------------------------------------------------------------------------
// Update notification (original functionality preserved)
// ---------------------------------------------------------------------------

chrome.runtime.onInstalled.addListener(({ previousVersion, reason }) => {
  if (reason === 'update') {
    const currentVersion = chrome.runtime.getManifest().version;
    chrome.notifications.create('updated', {
      type: 'basic',
      title: 'SageDLP',
      message: `Updated from ${previousVersion} to ${currentVersion}`,
      iconUrl: '/images/icon128.png',
      buttons: [{ title: 'Github Releases' }, { title: 'Uninstall' }],
    });
  }
});

chrome.notifications.onButtonClicked.addListener(
  (notificationId, buttonIndex) => {
    console.log(notificationId, buttonIndex);
    if (notificationId === 'updated') {
      switch (buttonIndex) {
        case 0:
          chrome.tabs.create({
            url: 'https://github.com/ID-VerNe/sage-dlp/releases',
          });
          break;
        case 1:
          chrome.management.uninstallSelf({ showConfirmDialog: true });
          break;
      }
    }
  },
);

// ---------------------------------------------------------------------------
// Save-file message listener for Firefox (original functionality preserved)
// ---------------------------------------------------------------------------

chrome.runtime.onMessage.addListener(async (message, sender, sendResponse) => {
  const { type, target, data } = message || {};
  if (target !== 'background') return;
  if (type === 'save') {
    const { text, name, format, saveAs } = data || {};
    await saveToFile(text, name, format, saveAs);
    sendResponse('done');
    return true;
  }
  return true;
});